title: WLH's Homepage
page-top-title: Yourname
top-section-bg-text: The everyday life that we experience every day might actually be a continuous series of miracles.
home-subtitle: 吴林浩&ensp;|&ensp;华中科技大学
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
